apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-test2-deployment-prod
  namespace: technical-test2
  labels:
    app: technical-test2-app-prod
    env: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: technical-test2-app-prod
  template:
    metadata:
      labels:
        app: technical-test2-app-prod
    spec:
      containers:
      - name: npm
        image: 378736163542.dkr.ecr.us-east-2.amazonaws.com/technical-test2:appversion
        ports:
        - containerPort: 3300