apiVersion: v1
kind: Service
metadata:
  name: technical-test2-service-prod
  namespace: technical-test2
  labels:
    app: technical-test2-app-prod
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: technical-test2-app-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3300