apiVersion: v1
kind: Service
metadata:
  name: technical-test2-svc
  namespace: techical-test2
  labels:
    app: techical-test2
    env: prod
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3300
  selector:
    app: techical-test2