apiVersion: v1
kind: Service
metadata:
  name: technical-test2-service-devlopment
  namespace: technical-test2
  labels:
    app: technical-test2-app
    env: dev
spec:
  type: LoadBalancer
  selector:
    app: technical-test2-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3300